<MyRoot>:

    random_label: random_label

    BoxLayout:
        orientation: "vertical"
#        Label:
#            # textː "🅰️🈷️🈂️🈷️🈶🈯🉐🈹🈚🈲🉑🈸🈴🈳㊗️㊙️🈺🈵"
#            text: "   🤖     AЉ话"
#            #text: "Robotic Polyglot"
#            font_size: 64
#            color: 0.92, 0.45, 0, 1
        Label:
            text: "Robotic Polyglot"
            font_size: 64
            color: 0.92, 0.45, 0, 1
        Label:
            id: random_label
            text: "-"
            font_size: 64
        Button:
            text: "Generate"
            font_size: 32
            size: 100, 50
            on_press: root.generate_number()